### ISSUE TITLE
delete or update your project

### ISSUE THREAD

**Issue by ogronome** [heyValdemar/keycloak-traefik-letsencrypt-docker-compose#3]
The whole yml is a piece of desinformation. Many variables are outdated and silently do not work (so you start with in-memory mode)...

**Comment by heyvaldemar** [comment]
> The whole yml is a piece of desinformation. Many variables are outdated and silently do not work (so you start with in-memory mode)...

It's not true. It's working perfectly fine for me.

What kind of issues do you have?

You can join my Discord server and ask questions https://discord.gg/AJQGCCBcqf
