### ISSUE TITLE
Install Keycloak with another application using Traefik

### ISSUE THREAD

**Issue by teguh02** [heyValdemar/keycloak-traefik-letsencrypt-docker-compose#4]
Hi Valdemar
My name Is Teguh, many big thanks for your docker compose configuration, because hard to install keycloak for myself, and finaly i found your docker compose config to make easier me, but now how i can install a laravel application besides keycloak using your Traefik docker compose configuration?

For example :
My Traefik : traefik.teguh.com
My Keycloak : sso.teguh.com
My hopes laravel app : app.teguh.com

How i can add my laravel application when i was installed the keycloak and traefik before?

Thanks

**Comment by heyvaldemar** [comment]
hey @teguh02, let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
