### ISSUE TITLE
Upgrade to Keycloak 26.0.0

### ISSUE THREAD

**Issue by wahidustoz** [heyValdemar/keycloak-traefik-letsencrypt-docker-compose#8]
H, can you help upgrade the keycloak version to the latest. I tried manually upgrading, but due to configuration changes new version isnt support.

**Comment by heyvaldemar** [comment]
hey @wahidustoz,

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
